language: java
env:
  - ACTIVATOR_VERSION=1.2.12 \
    ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip \
    ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE} \
    ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal/activator \
    HEROKU_APP=deploy-test
install:
  - sudo wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
script:
  - chmod a+x ./herokuEnviroment.sh
  - ./herokuEnviroment.sh
notifications:
  email: false
deploy:
  provider: heroku
  api_key: "ec5cd58f-8c94-4122-8fec-6202ac404af9"
  app: ${HEROKU_APP}